stages:
  - build
  - deploy
variables:
  GIT_SSL_NO_VERIFY: "true"

build-enapso-sdk:
  stage: build
  image: docker:latest
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/jupyter-lab:latest ./
    - docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker push ${CI_REGISTRY_IMAGE}/jupyter-lab:latest

deploy-enapso-sdk:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  variables:
    KUBE_NAMESPACE: "enapso-dev"
  environment:
    name: enapso-dev
  script:
    - |
      kubectl config get-contexts
      kubectl config use-context sem42/all-projects/enapso-ebu-cdk:ebu-cdk
      kubectl get pods
      kubectl delete --namespace $KUBE_NAMESPACE -f deployment.yaml
      kubectl delete secret gitlab-registry-enapso-ebu-cdk --namespace $KUBE_NAMESPACE || true
      kubectl create secret docker-registry gitlab-registry-enapso-ebu-cdk --namespace $KUBE_NAMESPACE --docker-server="$CI_REGISTRY" --docker-username="$CI_DEPLOY_USER" --docker-password="$CI_DEPLOY_PASSWORD" --docker-email="$GITLAB_USER_EMAIL" -o yaml --dry-run=client | kubectl apply -f -
      kubectl apply --namespace $KUBE_NAMESPACE -f deployment.yaml