version: '3'
networks:
    isolated-network:
        driver: bridge
services:
  jupyter-lab:
        container_name: jupyter-lab
        build:
            context: ./
            dockerfile: Dockerfile
        image: enapso/jupyter-lab
        ports:
            - "8888:8888"
        networks:
        - isolated-network
        extra_hosts:
        - "host.docker.internal:host-gateway"